### ISSUE TITLE
bpfman: Can we support gRPC API to operate ebpf maps?

### ISSUE THREAD

**Issue by spring-cxz** [bpfman/bpfman#1272]
Hi

I am a new user of bpfman. I recently reviewed the relevant documentation and source code implementation of bpfman. It is really a very convenient tool for ebpf users. But there is a small problem. I found that there is no gRPC operation interface to operate the ebpf maps. So I'd like to know what was the reason for considering not supporting the map manipulation API in the first place?

thanks.

**Comment by dave-tucker** [comment]
@spring-cxz Hi! Thanks for opening an issue.
There are a couple of reasons for this:

1. Performance: Map operations should happen as quickly as possible. Adding gRPC overhead didn't seem advisable.
1. Dependencies: Not all languages have gRPC bindings, but all should be able to make sys calls
1. Data Modelling: In order to support any type of RPC we'd have probably need to come up with a nicer way of modelling the data inside the maps instead of requiring that we end user application to provide well-formed map values.
1. Semantics: Not all map operations are supported on all map types, again making this hard to model over any type of RPC
1. Security: We were concerned about allowing map operations from outside of a given node scope

For example:
https://github.com/bpfman/bpfman/blob/main/examples/go-xdp-counter/main.go#L57-L58

And then interacting with a map here:
https://github.com/bpfman/bpfman/blob/main/examples/go-xdp-counter/main.go#L158-L192

Was there a specifc use you had in mind for interacting with maps over RPC?

**Comment by spring-cxz** [comment]
@dave-tucker  
Thank you very much for your answer. The reason I initially thought about using grpc to operate on the map was to prevent users from directly operating on the map file, so that the way of interacting with bpf might be more unified. But as you said, there are many types of maps and the operation methods are different, so it is really difficult to take over. 

I don't have any other questions. Please close this issue. Thanks again.
